
import { CourseModuleData } from './types';

export const COURSE_MODULES: CourseModuleData[] = [
  {
    id: 'course_detail',
    status: 'Premium',
    icon: '🎓',
    title: 'SPI Course Curriculum',
    description: 'An expansive, in-depth guide covering every topic on the ARDMS Sonography Principles & Instrumentation (SPI) exam outline. This is your foundation for success.',
    features: ['100+ Detailed Topics', 'Interactive Explanations', 'AI-Powered Study Plan', 'Module Quizzes', 'Key Takeaways & Exam Focus Sections'],
  },
  {
    id: 'waves',
    status: 'Core',
    icon: '🌊',
    title: 'Propagation Speed & Acoustic Variables',
    description: 'Understand the fundamental principles of sound waves. Learn about acoustic variables, propagation speed, and how tissue characteristics affect the ultrasound beam.',
    features: ['Interactive Wave Simulator', 'Tissue Speed Comparison', 'Acoustic Variable Visualizer', 'Wavelength & Frequency Relationship'],
  },
  {
    id: 'transducers',
    status: 'Core',
    icon: '⚡',
    title: 'Fundamentals of Ultrasound Transducers',
    description: 'A deep dive into exploring Transducers & Transducer Components. Learn about the piezoelectric effect, component trade-offs, frequency selection, and bandwidth.',
    features: ['Piezoelectric Effect Animations', 'Damping & Resolution Trade-off', 'Frequency vs. Resolution/Penetration', 'Bandwidth & Pulse Duration', 'Clinical Frequency Selection'],
  },
  {
    id: 'resolution',
    status: 'Core',
    icon: '🔍',
    title: 'Axial & Lateral Resolution',
    description: 'Master the critical concepts of image resolution. Learn what factors determine detail resolution and how to optimize them for the best possible image.',
    features: ['Axial vs. Lateral Simulation', 'SPL & Pulse Duration Effects', 'Beam Width Visualization', 'Focusing Impact on Resolution'],
  },
  {
    id: 'pulsed',
    status: 'Core',
    icon: '📡',
    title: 'Pulsed Wave Operation',
    description: 'Dive into the mechanics of pulsed ultrasound. Understand concepts like Pulse Repetition Frequency (PRF), Pulse Repetition Period (PRP), and duty factor.',
    features: ['PRF & Depth Relationship', 'Duty Factor Calculator', 'Interactive Pulse Diagram', 'Range Ambiguity Simulation'],
  },
  {
    id: 'doppler',
    status: 'Core',
    icon: '🎯',
    title: 'Doppler Physics & Imaging Modes',
    description: 'Explore the Doppler effect and its application in medical imaging. Learn about spectral, color, and power Doppler, and the nuances of the Doppler equation.',
    features: ['Interactive Doppler Shift Demo', 'Color Map & Variance Controls', 'Spectral Waveform Analysis', 'Doppler Angle Effects'],
  },
  {
    id: 'knobology',
    status: 'Premium',
    icon: '🎛️',
    title: 'System Optimization (Knobology)',
    description: 'An interactive ultrasound simulator where you can manipulate system controls and see their immediate effect on a phantom image. Master the art of optimization.',
    features: ['Virtual Ultrasound Console', 'Real-time Image Feedback', 'TGC, Gain, DR, & Focus Controls', 'Guided Optimization Scenarios'],
  },
  {
    id: 'artifacts',
    status: 'Core',
    icon: '🎨',
    title: 'Common Imaging Artifacts',
    description: 'Learn to identify and understand the most common artifacts in ultrasound imaging. Know when they help and when they hinder diagnosis.',
    features: ['Artifact Generation Simulator', 'Shadowing vs. Enhancement', 'Reverberation & Comet Tail Demo', 'Side Lobe & Grating Lobe Effects'],
  },
  {
    id: 'advanced_artifacts',
    status: 'Advanced',
    icon: '🌌',
    title: 'Advanced Artifacts',
    description: 'Go beyond the basics to understand more complex and subtle artifacts like beam width, slice thickness, mirror image, and speed error.',
    features: ['Mirror Image Simulation', 'Speed Error Calculator', 'Slice Thickness Artifact Demo', 'Interactive Beam Width Examples'],
  },
  {
    id: 'harmonics',
    status: 'Advanced',
    icon: '🎵',
    title: 'Harmonic Imaging',
    description: 'Discover the principles of Tissue Harmonic Imaging (THI). Learn how it improves image quality by reducing artifacts and improving signal-to-noise ratio.',
    features: ['Fundamental vs. Harmonic Imaging', 'Pulse Inversion Phasing Demo', 'Artifact Reduction Comparison'],
  },
  {
    id: 'elastography',
    status: 'Advanced',
    icon: '🧱',
    title: 'Elastography',
    description: 'Understand the physics of elastography. Learn how ultrasound can be used to assess tissue stiffness, a key indicator for diagnosing various pathologies.',
    features: ['Strain vs. Shear Wave Explained', 'Interactive Stiffness Map', 'ARFI Push Pulse Simulation'],
  },
  {
    id: 'contrast_agents',
    status: 'Advanced',
    icon: '✨',
    title: 'Contrast Agents',
    description: 'Explore the use of microbubble contrast agents in ultrasound. Learn about their physical properties, resonance behavior, and clinical applications.',
    features: ['Microbubble Resonance Simulator', 'Mechanical Index Effects', 'Contrast-Specific Imaging Modes'],
  },
  {
    id: '3d_4d',
    status: 'Advanced',
    icon: '🧊',
    title: '3D/4D Imaging',
    description: 'Learn the principles of volume imaging. Understand the techniques for data acquisition, volume rendering, and multi-planar reconstruction.',
    features: ['3D Data Acquisition Demo', 'Interactive Volume Rendering', 'Multi-Planar Reconstruction (MPR) Slicer', 'Real-time 4D Animation'],
  },
  {
    id: 'm_mode',
    status: 'Advanced',
    icon: '📈',
    title: 'M-Mode Imaging',
    description: 'Master the "ice pick" view of ultrasound. Learn how M-Mode provides high temporal resolution for analyzing moving structures, crucial in cardiac and fetal imaging.',
    features: ['Interactive M-Mode Line Placement', 'Temporal Resolution Comparison', 'Cardiac Valve Motion Analysis'],
  },
  {
    id: 'hemodynamics',
    status: 'Core',
    icon: '❤️',
    title: 'Hemodynamics',
    description: 'Apply physics principles to blood flow. Understand pressure-flow relationships, continuity, and the Bernoulli and Poiseuille equations.',
    features: ['Interactive Flow Dynamics Sim', 'Bernoulli Effect Visualizer', 'Stenosis & Flow Velocity Demo', 'Continuity Rule Calculator'],
  },
  {
    id: 'safety',
    status: 'Core',
    icon: '🛡️',
    title: 'Bioeffects and Safety',
    description: 'Learn about the potential biological effects of ultrasound and the principles of safe scanning. Understand TI, MI, and the ALARA principle.',
    features: ['Thermal Index (TI) Simulator', 'Mechanical Index (MI) Explained', 'ALARA Principle Scenarios'],
  },
  {
    id: 'biomedical_physics',
    status: 'Core',
    icon: '🔬',
    title: 'Biomedical Physics',
    description: 'A survey of key physics concepts relevant to ultrasound, including intensity, power, pressure, and the decibel scale.',
    features: ['Interactive Decibel Calculator', 'Intensity & Power Visualizer', 'Pressure & Amplitude Relationship'],
  },
  {
    id: 'abdominal',
    status: 'Clinical',
    icon: '👨‍⚕️',
    title: 'Clinical Application: Abdomen',
    description: 'Apply physics concepts to abdominal scanning. Understand the unique challenges and optimization techniques for imaging the liver, gallbladder, and kidneys.',
    features: ['Liver Tissue Characterization', 'Gallstone Shadowing Demo', 'Renal Cyst vs. Solid Mass'],
  },
  {
    id: 'vascular',
    status: 'Clinical',
    icon: '🩸',
    title: 'Clinical Application: Vascular',
    description: 'Focus on the physics of vascular ultrasound. Master stenosis assessment, differentiate flow patterns, and understand common vascular pathologies.',
    features: ['Carotid Stenosis Measurement Lab', 'Waveform Analysis (Triphasic, Biphasic)', 'Aliasing & PRF Correction'],
  },
  {
    id: 'msk',
    status: 'Clinical',
    icon: '🦴',
    title: 'Clinical Application: MSK',
    description: 'Explore the dynamic world of Musculoskeletal (MSK) ultrasound. Learn about the critical concept of anisotropy, tendon pathology, and dynamic imaging techniques.',
    features: ['Anisotropy Explained Interactively', 'Tendon Tear Pathology Simulation', 'Dynamic Impingement Test'],
  },
  {
    id: 'clinical_case_simulator',
    status: 'Game',
    icon: '🧑‍⚕️',
    title: 'AI Clinical Case Simulator',
    description: 'Apply your physics knowledge in a real-world diagnostic challenge. Interact with an AI-powered patient case, generate ultrasound images, and make a diagnosis.',
    features: ['AI-Generated Patient Scenarios', 'On-Demand Image Generation', 'Interactive Diagnostic Reporting', 'Personalized AI Feedback'],
  },
   {
    id: 'processing',
    status: 'Premium',
    icon: '⚙️',
    title: 'Preprocessing vs. Postprocessing',
    description: 'Understand the difference between functions that can be changed on a live image versus a frozen one. Learn what happens to the raw data.',
    features: ['Interactive Control Panel', 'Live vs. Frozen Image Comparison', 'Signal Path Visualizer'],
  },
  {
    id: 'tgc',
    status: 'Premium',
    icon: '🎚️',
    title: 'Time Gain Compensation (TGC)',
    description: 'Master the art of TGCs. Learn how to compensate for attenuation to create a uniformly bright image from the near field to the far field.',
    features: ['Interactive TGC Curve', 'Real-time Image Update', 'Impact of Attenuation Demo'],
  },
  {
    id: 'dynamic_range',
    status: 'Premium',
    icon: '📊',
    title: 'Dynamic Range (Compression)',
    description: 'Learn how dynamic range affects image contrast. Understand how to adjust this control to visualize different tissue textures.',
    features: ['Interactive DR Slider', 'High vs. Low Contrast Demo', 'Grayscale Map Visualizer'],
  },
  {
    id: 'qa',
    status: 'Premium',
    icon: '✅',
    title: 'Quality Assurance',
    description: 'Explore the essentials of ultrasound system QA. Learn about the tests performed using phantoms to ensure the system is operating correctly.',
    features: ['Virtual QA Phantom', 'Dead Zone Measurement', 'Resolution Tests', 'Caliper Accuracy Check'],
  },
  {
    id: 'cardiac',
    status: 'Clinical',
    icon: '❤️',
    title: 'Clinical Application: Cardiac',
    description: 'Dive into the physics of cardiac imaging. Learn about phased array transducers, high frame rates, and the specific challenges of imaging a moving heart.',
    features: ['Phased Array Beam Steering', 'Frame Rate vs. Sector Width', 'M-Mode for Valve Motion'],
  },
  {
    id: 'study_guide',
    status: 'Game',
    icon: '📖',
    title: 'SPI Study Guide Challenge',
    description: 'Test your knowledge with our comprehensive AI-powered study guide. Generate flashcards and quizzes on demand to solidify your understanding of key concepts.',
    features: ['AI-Generated Flashcards', 'AI-Powered Quizzes', 'Covers All SPI Topics', 'Personalized Learning'],
  },
  {
    id: 'jeopardy',
    status: 'Game',
    icon: '🕹️',
    title: 'SPI Jeopardy Challenge',
    description: 'A fun, fast-paced game to test your knowledge across all major SPI categories. Compete against yourself to clear the board!',
    features: ['Classic Jeopardy Format', '5 Diverse SPI Categories', 'Progressive Difficulty', 'Interactive Scoreboard'],
  },
  {
    id: 'spi_mock_exam',
    status: 'Game',
    icon: '⏱️',
    title: 'SPI Mock Exam',
    description: 'Simulate the real SPI exam experience with a full-length, timed mock exam. Get a detailed breakdown of your performance and identify areas for improvement.',
    features: ['110 Questions, 2 Hours', 'Timed Exam Simulation', 'Performance Analytics', 'Covers Full SPI Outline', 'Builds Test-Taking Stamina'],
  },
  {
    id: 'escape_room',
    status: 'Game',
    icon: '🔐',
    title: 'The Phantom Lab Escape',
    description: 'You are locked in the ultrasound lab! Solve a series of physics-based puzzles and crack the codes to escape before time runs out.',
    features: ['Physics Logic Puzzles', 'Artifact Identification', 'Knobology Challenges', 'Immersive Escape Room Vibe'],
  },
  {
    id: 'crossword',
    status: 'Game',
    icon: '🧩',
    title: 'Physics Crossword',
    description: 'Test your vocabulary and definition recall with this interactive ultrasound physics crossword puzzle.',
    features: ['Classic Crossword Gameplay', 'Interactive Hints', 'Instant Feedback', 'Covers Key Terminology'],
  },
  {
    id: 'bingo',
    status: 'Game',
    icon: '🎱',
    title: 'Physics Bingo',
    description: 'A fast-paced game of recall. Listen to the definition and mark the correct term on your board. Can you get 5 in a row?',
    features: ['Randomized Game Boards', 'Term-Definition Matching', 'Fun & Fast-Paced', 'Great for Quick Review'],
  },
  {
    id: 'personalized_study',
    status: 'New!',
    icon: '🧬',
    title: 'AI Personalized Learning Engine',
    description: 'Generates a hyper-personalized lesson plan based on your Numerology, Astrology, and Learning Style.',
    features: ['Numerology Profile Calculation', 'VARK Learning Style Analysis', 'Custom Lesson Logic Matrix', 'AI-Generated Content'],
  },
];